---
- name: Instalar y ejecutar OpenSCAP
  hosts: all
  become: true
  tasks:
    - name: Instalar scap-security-guide y openscap
      dnf:
        name:
          - scap-security-guide
          - openscap-scanner
        state: present

    - name: Ejecutar escaneo con perfil RHEL7 STIG
      command: >
        oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig
        --results /tmp/openscap-results.xml
        /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
      register: scan_result
      changed_when: false

    - name: Mostrar resultado de OpenSCAP
      debug:
        var: scan_result.stdout_lines
