---
- name: Eliminar servicios innecesarios
  hosts: all
  become: true
  vars:
    packages_to_remove:
      - telnet
      - rsh
      - xinetd
      - vsftpd
      - ftp
  tasks:
    - name: Remover paquetes inseguros
      dnf:
        name: "{{ packages_to_remove }}"
        state: absent
