---
- name: OpenSCAP Scan on RHEL 8.10
  hosts: all
  become: yes
  tasks:

    - name: Install OpenSCAP packages
      yum:
        name:
          - scap-security-guide
          - openscap-scanner
        state: present

    - name: Run OpenSCAP scan
      command: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report /tmp/openscap_report.html /usr/share/xml/scap/ssg/content/ssg-rhel8-xccdf.xml
      register: openscap_result
      changed_when: openscap_result.rc != 0

    - name: Fetch OpenSCAP report
      fetch:
        src: /tmp/openscap_report.html
        dest: ./openscap_report.html
        flat: yes
