---
- name: Validar pre-requisitos de actualización a RHEL 8.x y guardar output
  hosts: all
  become: true
  vars:
    output_dir: "/tmp"
    output_filename: "ansible_output_{{ ansible_date_time.year }}_{{ ansible_date_time.month }}_{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}_{{ ansible_date_time.second }}.txt"

  tasks:
    - name: Recopilar información sobre los paquetes instalados
      ansible.builtin.package_facts:
        manager: auto

    - name: Verificar versión actual de RHEL
      command: cat /etc/redhat-release
      register: rhel_version
      failed_when: rhel_version.stdout is not search("Red Hat Enterprise Linux release 8")

    - name: Mostrar versión actual de RHEL
      debug:
        msg: "Versión actual de RHEL: {{ rhel_version.stdout }}"

    - name: Verificar suscripción de RHEL
      command: subscription-manager status
      register: subscription_status
      failed_when: subscription_status.rc != 0

    - name: Mostrar estado de suscripción
      debug:
        msg: "Estado de suscripción: {{ subscription_status.stdout }}"

    - name: Guardar output del playbook en el filesystem local
      ansible.builtin.lineinfile:
        path: "{{ output_dir }}/{{ output_filename }}"
        line: "{{ item }}"
        create: yes
      with_items:
        - "Versión actual de RHEL: {{ rhel_version.stdout }}"
        - "Estado de suscripción: {{ subscription_status.stdout }}"
      delegate_to: localhost
      run_once: true
