---
- name: Informe previo a la actualización de RHEL 8.x a RHEL 8.10
  hosts: all
  become: true
  vars:
    output_dir: "/tmp"
    output_filename: "pre_upgrade_report_{{ ansible_date_time.year }}_{{ ansible_date_time.month }}_{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}_{{ ansible_date_time.second }}.txt"

  tasks:
    - name: Verificar versión actual de RHEL
      command: cat /etc/redhat-release
      register: rhel_version

    - name: Mostrar versión actual de RHEL
      debug:
        msg: "Versión actual de RHEL: {{ rhel_version.stdout }}"

    - name: Verificar suscripción de RHEL
      command: subscription-manager status
      register: subscription_status
      failed_when: subscription_status.rc != 0

    - name: Mostrar estado de suscripción
      debug:
        msg: "Estado de suscripción: {{ subscription_status.stdout }}"

    - name: Obtener lista de paquetes disponibles para instalación
      command: dnf list available --quiet
      register: available_packages
      changed_when: false

    - name: Mostrar lista de paquetes disponibles para instalación
      debug:
        msg: "{{ available_packages.stdout_lines }}"
      when: available_packages.stdout_lines | length > 0

    - name: Guardar informe previo a la actualización en el filesystem del servidor remoto
      ansible.builtin.lineinfile:
        path: "{{ output_dir }}/{{ output_filename }}"
        create: yes
      with_items:
        - "Versión actual de RHEL: {{ rhel_version.stdout }}"
        - "Estado de suscripción: {{ subscription_status.stdout }}"
        - "Paquetes disponibles para instalación: {{ available_packages.stdout_lines | join(', ') }}"
