---
- name: Validate RHEL prerequisites and generate report
  hosts: all
  become: yes
  vars:
    report_file: /tmp/rhel_prerequisites_report.txt
    required_packages:
      - vim
      - curl
      - wget
      - net-tools
  tasks:
    - name: Gather system facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'distribution'
          - 'pkg_mgr'

    - name: Check RHEL version
      ansible.builtin.set_fact:
        rhel_version: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

    - name: Check subscription status
      ansible.builtin.command: subscription-manager status
      register: subscription_status
      changed_when: false
      failed_when: false

    - name: Get subscription details
      ansible.builtin.command: subscription-manager list --installed
      register: subscription_details
      changed_when: false
      failed_when: false

    - name: Check required packages
      ansible.builtin.package:
        name: "{{ required_packages }}"
        state: present
      check_mode: yes
      register: package_check
      failed_when: false

    - name: Count missing packages
      ansible.builtin.set_fact:
        missing_packages: "{{ package_check.results | select('attr', 'changed') | list | length }}"
        missing_packages_list: "{{ package_check.results | select('attr', 'changed') | map('attr', 'name') | list }}"

    - name: Create report content
      ansible.builtin.set_fact:
        report_content: |
          RHEL Prerequisites Report
          =======================
          Generated on: {{ ansible_date_time.iso8601 }}
          Hostname: {{ ansible_hostname }}
          
          1. RHEL Version
          ---------------
          {{ rhel_version }}
          
          2. Subscription Status
          ---------------------
          {{ subscription_status.stdout | default('No subscription information available') }}
          
          3. Subscription Details
          ----------------------
          {{ subscription_details.stdout | default('No subscription details available') }}
          
          4. Package Status
          ----------------
          Required packages: {{ required_packages | join(', ') }}
          Missing packages count: {{ missing_packages }}
          Missing packages: {{ missing_packages_list | join(', ') | default('None') }}

    - name: Generate report file
      ansible.builtin.copy:
        content: "{{ report_content }}"
        dest: "{{ report_file }}"
        mode: '0644'
      delegate_to: localhost
      when: not ansible_check_mode

    - name: Ensure report file exists on target
      ansible.builtin.file:
        path: "{{ report_file }}"
        state: touch
        mode: '0644'
      when: not ansible_check_mode

    - name: Copy report to target
      ansible.builtin.copy:
        content: "{{ report_content }}"
        dest: "{{ report_file }}"
        mode: '0644'
      when: not ansible_check_mode

  handlers:
    - name: Clean up temporary files
      ansible.builtin.file:
        path: "{{ report_file }}"
        state: absent
      when: ansible_check_mode

  pre_tasks:
    - name: Verify sudo privileges
      ansible.builtin.command: whoami
      register: whoami_result
      changed_when: false
      failed_when: whoami_result.stdout != 'root'

  post_tasks:
    - name: Display report location
      ansible.builtin.debug:
        msg: "Report generated at: {{ report_file }}"
      when: not ansible_check_mode
